-- 코드를 입력하세요
WITH VALUE AS (
    SELECT B.CATEGORY, B.AUTHOR_ID, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
    FROM BOOK AS B
    JOIN BOOK_SALES AS S
    ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE LIKE '2022-01%'
    GROUP BY B.CATEGORY, B.AUTHOR_ID
)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, V.CATEGORY, V.TOTAL_SALES
FROM AUTHOR AS A
JOIN VALUE AS V
ON A.AUTHOR_ID = V.AUTHOR_ID
ORDER BY A.AUTHOR_ID, V.CATEGORY DESC