-- 코드를 입력하세요
WITH VALUE AS (
    SELECT DISTINCT H.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    JOIN CAR_RENTAL_COMPANY_CAR AS C
    ON H.CAR_ID = C.CAR_ID
    WHERE H.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-11-01'
        AND DATE_FORMAT(START_DATE, '%Y-%m-%d') < '2022-12-01'
    )
    AND C.CAR_TYPE IN ('SUV', '세단')
)

SELECT V.CAR_ID, V.CAR_TYPE,
ROUND(((V.DAILY_FEE * 30) * (100 - P.DISCOUNT_RATE) / 100)) AS FEE
FROM VALUE AS V
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON V.CAR_TYPE = P.CAR_TYPE
WHERE P.DURATION_TYPE LIKE '30%'
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, V.CAR_TYPE, V.CAR_ID DESC