-- 코드를 입력하세요
WITH VALUE AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO AS R
JOIN VALUE AS V
ON V.MAX_FAVORITES = R.FAVORITES
AND R.FOOD_TYPE = V.FOOD_TYPE
ORDER BY R.FOOD_TYPE DESC