-- 코드를 입력하세요
WITH BOARD AS (
    SELECT WRITER_ID, COUNT(*) AS BOARD_COUNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING BOARD_COUNT >= 3
    )
    
SELECT U.USER_ID, NICKNAME,
CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
CONCAT(SUBSTRING(TLNO, 1,3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) AS 전화번호
FROM BOARD AS B
JOIN USED_GOODS_USER AS U
ON B.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC