-- 코드를 입력하세요
WITH VALUE AS (
    SELECT WRITER_ID, COUNT(*) AS BOARD_COUNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING BOARD_COUNT >= 3
    )

SELECT U.USER_ID, U.NICKNAME,
CONCAT_WS('', U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS 전체주소,
CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS 전화번호
FROM VALUE AS V
JOIN USED_GOODS_USER AS U
ON V.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC