-- 코드를 입력하세요
WITH SCORE AS (
    SELECT R.REST_ID, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
    FROM REST_INFO AS I
    JOIN REST_REVIEW AS R
    ON I.REST_ID = R.REST_ID
    WHERE I.ADDRESS LIKE '서울%'
    GROUP BY R.REST_ID
    )

SELECT R.REST_ID, R.REST_NAME, R.FOOD_TYPE, R.FAVORITES,
R.ADDRESS, S.SCORE
FROM SCORE AS S
JOIN REST_INFO AS R
ON S.REST_ID = R.REST_ID
ORDER BY SCORE DESC, R.FAVORITES DESC