-- 코드를 입력하세요

WITH TOTAL_COUNT AS (
    SELECT COUNT(USER_ID) AS TOTAL_PEOPLE
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)

SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS,
ROUND((COUNT(DISTINCT O.USER_ID) / TOTAL_COUNT.TOTAL_PEOPLE), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS O
JOIN USER_INFO AS U
ON O.USER_ID = U.USER_ID, TOTAL_COUNT
WHERE U.JOINED LIKE '2021%'
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH