-- 코드를 입력하세요
WITH VALUE AS (
    SELECT HOST_ID, COUNT(*) AS HOST_COUNT
    FROM PLACES
    GROUP BY HOST_ID
    HAVING HOST_COUNT > 1
)

SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES AS P
JOIN VALUE AS V
ON P.HOST_ID = V.HOST_ID
ORDER BY P.ID