-- 코드를 입력하세요
WITH VALUE AS (
    SELECT F.FLAVOR, SUM(J.TOTAL_ORDER + F.TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF AS F
    JOIN JULY AS J
    ON F.FLAVOR = J.FLAVOR
    GROUP BY J.FLAVOR
)

SELECT FLAVOR
FROM VALUE
ORDER BY TOTAL_ORDER DESC
LIMIT 3