-- 코드를 입력하세요
WITH VALUE AS (
    SELECT A.APNT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD, A.PT_NO
    FROM APPOINTMENT AS A
    JOIN DOCTOR AS D
    ON A.MDDR_ID = D.DR_ID
    WHERE A.APNT_YMD LIKE '2022-04-13%'
    AND A.APNT_CNCL_YN LIKE 'N'
    AND A.MCDP_CD LIKE 'CS'
    )

SELECT V.APNT_NO, P.PT_NAME, P.PT_NO, V.MCDP_CD, V.DR_NAME, V.APNT_YMD
FROM PATIENT AS P
JOIN VALUE AS V
ON V.PT_NO = P.PT_NO
ORDER BY V.APNT_YMD