-- 코드를 입력하세요
WITH APPOINT AS (
    SELECT A.APNT_NO, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
    FROM APPOINTMENT AS A
    JOIN DOCTOR AS D
    ON A.MDDR_ID = D.DR_ID
    WHERE A.APNT_YMD LIKE '2022-04-13%'
    AND A.MCDP_CD LIKE 'CS'
    AND A.APNT_CNCL_YN = 'N'
    )

SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, A.DR_NAME, A.APNT_YMD
FROM APPOINT AS A
JOIN PATIENT AS P
ON A.PT_NO = P.PT_NO
ORDER BY A.APNT_YMD