WITH RECURSIVE CTE AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM + 1
    FROM CTE
    WHERE NUM < 23
),

ANIMAL AS (
    SELECT HOUR(DATETIME) AS DATETIME, COUNT(*) AS CNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
)

SELECT CTE.NUM AS HOUR, IFNULL(A.CNT, 0) AS COUNT
FROM ANIMAL AS A
RIGHT JOIN CTE
ON CTE.NUM = A.DATETIME
ORDER BY HOUR