-- 코드를 입력하세요
WITH RECURSIVE VALUE AS(
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM + 1
    FROM VALUE
    WHERE NUM <= 22
)

SELECT V.NUM AS HOUR, COUNT(O.ANIMAL_ID) AS COUNT
FROM VALUE AS V
LEFT JOIN ANIMAL_OUTS AS O
ON HOUR(O.DATETIME) = V.NUM
GROUP BY V.NUM
ORDER BY HOUR