-- 코드를 작성해주세요
WITH CATE AS (
    SELECT D.ID,
    GROUP_CONCAT(S.CATEGORY) AS CATEGORY
    FROM SKILLCODES AS S
    JOIN DEVELOPERS AS D
    ON S.CODE & D.SKILL_CODE
    GROUP BY D.ID
    HAVING CATEGORY LIKE '%Front End%'
    )

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM CATE
JOIN DEVELOPERS AS D
ON CATE.ID = D.ID
ORDER BY D.ID