-- 코드를 입력하세요
WITH VALUE AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
    LIMIT 1
    ),

RESULT AS (
    SELECT M.MEMBER_ID, M.MEMBER_NAME
    FROM MEMBER_PROFILE AS M
    JOIN VALUE AS V
    ON M.MEMBER_ID = V.MEMBER_ID
)

SELECT R.MEMBER_NAME, E.REVIEW_TEXT, 
DATE_FORMAT(E.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM RESULT AS R
JOIN REST_REVIEW AS E
ON R.MEMBER_ID = E.MEMBER_ID
ORDER BY E.REVIEW_DATE, E.REVIEW_TEXT