-- 코드를 입력하세요
WITH VALUE AS (
    SELECT M.MEMBER_NAME, R.MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW AS R
    JOIN MEMBER_PROFILE AS M
    ON R.MEMBER_ID = M.MEMBER_ID
    GROUP BY R.MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
    LIMIT 1
)

SELECT V.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS R
JOIN VALUE AS V
ON R.MEMBER_ID = V.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT