-- 코드를 입력하세요
WITH VALUE AS (
    SELECT CAR_ID, COUNT(*) AS RECORD
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d')
    BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING RECORD >= 5
)

SELECT MONTH(START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
JOIN VALUE AS V
ON C.CAR_ID = V.CAR_ID
WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d')
BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, C.CAR_ID DESC