-- 코드를 작성해주세요
WITH DEV AS (
    SELECT D.ID,
    GROUP_CONCAT(S.NAME) AS SKILLNAME
    FROM DEVELOPERS AS D
    JOIN SKILLCODES AS S
    ON D.SKILL_CODE & S.CODE
    GROUP BY D.ID
    HAVING SKILLNAME LIKE '%Python%'
    OR SKILLNAME LIKE '%C#%'
    )
    
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEV
JOIN DEVELOPERS AS D
ON DEV.ID = D.ID
ORDER BY D.ID