-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE LIKE '세단'
AND DATE_FORMAT(H.START_DATE, '%Y-%m-%d') BETWEEN '2022-10-01' AND '2022-10-31'
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC