-- 코드를 입력하세요
WITH VALUE AS (
    SELECT MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)

SELECT DISTINCT P.CATEGORY, VALUE.PRICE AS MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT AS P
JOIN VALUE
ON P.PRICE = VALUE.PRICE
WHERE CATEGORY IN ('과자', '김치', '식용유', '국')
ORDER BY MAX_PRICE DESC